[package]
name = "streebog"
version = "0.9.2"
description = "Streebog (GOST R 34.11-2012) hash function"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"
documentation = "https://docs.rs/streebog"
repository = "https://github.com/RustCrypto/hashes"
keywords = ["crypto", "streebog", "gost", "hash", "digest"]
categories = ["cryptography", "no-std"]

[dependencies]
digest = { version = "0.10.0-pre.3", features = ["core-api"] }

[dev-dependencies]
digest = { version = "0.10.0-pre.3", features = ["dev"] }
hex-literal = "0.2"

[features]
default = ["std"]
std = ["digest/std"]
